services:
  dev:
    build:
      context: .
      target: dev
    container_name: astro-dev
    profiles: [dev]
    networks:
      - astro
    ports:
      - 8080:4321
    volumes:
      - ".:/app"
  test:
    build:
      context: .
      target: runtime
    container_name: astro-test
    profiles: [test]
    networks:
      - astro
    ports:
      - 4321:4321
  runtime:
    build:
      context: .
      target: runtime
    container_name: astro-runtime
    profiles: [runtime]
    networks:
      - astro
networks:
  astro:
    driver: bridge
    name: astro
